channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=23.2.1
  - pre-commit=3.5.0
  - python=3.12.0
  - ruff=0.4.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - scikit-image>=0.18.0
  - opencv>=4.5.0
  - tifffile>=2021.11.0
  - pillow>=8.3.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - ipympl>=0.8.0
